### ISSUE TITLE
Borlix

### ISSUE THREAD

**Issue by adolfosilva** [osm10/Reverse_Engineering#1]
Queres televisão à pala Oliver?

**Comment by osm10** [comment]
Os canais nacionais não são de borla?! Mesmo que os vejas ou não!... já estão incluidos no faturamento da luz. 
Depois existe uma coisa chamada de www (World Wide Web), não sei se conheces?!!
Oliver?! Quem é esse gajo?!! Esse gajo não percebe nada disto.
Mas eu vou ser teu amigo e por isso vou te dar mais umas pistas...  :)

**Comment by adolfosilva** [comment]
Quem não percebe nada disto sou eu. Andas a ver Mr. Robot e depois dá nisto. :)

**Comment by osm10** [comment]
O Mr. Robot é que me anda a ver.  Isto aqui é uma série de programação de baixo nivel. Tens que passar a progamação de alto nivel, Adolfo. Billions é o que está a dar agora.  :)

Já agora tens algum tdt da marca BestBuy aí por casa?!!

**Comment by adolfosilva** [comment]
Claro, dai ser uma série de qualidade.

Não, não tenho.

Não ando a ver commits... já desististe homem?

**Comment by osm10** [comment]
Não... há duas maneiras de fazer a coisa. Ou escolho a maneira mais fácil ou escolho a maneira mais dificil?!!  :)
